# -*- coding: utf-8 -*-
"""model_v5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GVi0cmeL3OVAk1IjtHfHfOh8UWOxvr3V
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

# CUDA?
cuda = torch.cuda.is_available()
print("CUDA Available?", cuda)

class Net(nn.Module):
    #This defines the structure of the NN.
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Sequential(
            nn.Conv2d(1, 4, 3, padding=0),
            nn.ReLU(),
            nn.BatchNorm2d(4),
            nn.Dropout(0.1)
        ) # 26*26*4

        self.conv2 = nn.Sequential(
            nn.Conv2d(4, 8, 3, padding=0),
            nn.ReLU(),
            nn.BatchNorm2d(8),
            nn.Dropout(0.1),
            nn.MaxPool2d(2, 2)
        ) # 24*24*8 | 12*12*8

        self.trans1 = nn.Sequential(
            nn.Conv2d(8, 8, 1, padding=0),
            nn.ReLU(),
            nn.BatchNorm2d(8),
            nn.Dropout(0.1)
        ) # 12*12*8
        # increase it back to 16
        self.conv3 = nn.Sequential(
            nn.Conv2d(8, 16, 3, padding=0),
            nn.ReLU(),
            nn.BatchNorm2d(16),
            nn.Dropout(0.1)
            #nn.MaxPool2d(2, 2)
        ) # 10*10*16

        self.conv4 = nn.Sequential(
            nn.Conv2d(16, 32, 3, padding=0),
            nn.ReLU(),
            nn.BatchNorm2d(32),
            nn.Dropout(0.1),
            #nn.MaxPool2d(2, 2)
        ) # 8*8*32

        self.trans2 = nn.Sequential(
            nn.Conv2d(32, 16, 1, padding=0) ## bring down to 8
        ) # 8*8*16

        self.conv5 = nn.Sequential(
            nn.Conv2d(16, 16, 3, padding=0), ## take it from 8 to 16
            nn.ReLU(),
            nn.BatchNorm2d(16),
            nn.Dropout(0.1),
            #nn.MaxPool2d(2, 2)
        ) # 6*6*16

        self.conv6 = nn.Sequential(
            nn.Conv2d(16, 10, 3, padding=0),
            nn.ReLU(),
            nn.BatchNorm2d(10),
            nn.Dropout(0.1),
            #nn.MaxPool2d(2, 2)
        ) # 4*4*10

        self.conv7 = nn.Sequential(
            nn.Conv2d(10, 10, 1, padding=0),
            nn.AvgPool2d(kernel_size=4)
        ) # 4*4*10 | 1*1*10

    def forward(self, x):
      x = self.conv1(x)
      #print("size after 1st layer: " ,x.shape)
      x = self.conv2(x)
      x = self.trans1(x)
      x = self.conv3(x)
      #print("size after 2nd layer: " ,x.shape)
      x = self.conv4(x)
      x = self.trans2(x)
      x = self.conv5(x)
      x = self.conv6(x)
      x = self.conv7(x)
      #print("size after 4th layer: " ,x.shape)
      x = x.view(x.size(0), -1)
      #print("size after flattening: " ,x.shape)
      x = F.log_softmax(x, dim=1)
      return x